config/routes.rb
Ralencar::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  

  resources :contact_forms

  resources :jobs

  resources :posts do
    member do
      get 'hasNext'
      get 'to'
      get 'count'
      get 'index_of'
      get 'menu'
    end
  end

  match 'posts/:first/to/:last', :controller => 'posts', :action => 'find'
    

    namespace :admin do
      resources :posts
      resources :jobs
      resources :contact_forms

    end

  
  root :to => 'posts#show'

end

app/controllers/admin/contact_forms_controller.rb
class Admin::ContactFormsController < ApplicationController
	layout 'admin'
	
	# GET /contact_forms
	# GET /contact_forms.json
	def index
		@contact_forms = ContactForm.all
	
		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @contact_forms }
		end
	end
	
	# GET /contact_forms/1
	# GET /contact_forms/1.json
	def show
		@contact_form = ContactForm.find(params[:id])
	
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @contact_form }
		end
	end
	
	# DELETE /contact_forms/1
	# DELETE /contact_forms/1.json
	def destroy
		@contact_form = ContactForm.find(params[:id])
		@contact_form.destroy
	
		respond_to do |format|
			format.html { redirect_to contact_forms_url }
			format.json { head :no_content }
		end
	end
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  respond_to :json,:js,:html,:xml
  
  # GET /contact_forms
  # GET /contact_forms.json
  def index
    @post = Post.order("date DESC").last
    @count = Post.all.count
    @num_nexts = Post.where("date > :post_date", {:post_date => @post.date}).count
    @index_of = 0
    @contact_form = ContactForm.new(params[:contact_form])
    
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contact_forms }
    end
  end
  
  # GET /contact_forms/new
  # GET /contact_forms/new.json
  def new
    @contact_form = ContactForm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact_form }
    end
  end

  # POST /contact_forms
  # POST /contact_forms.json
  def create
    @contact_form = ContactForm.new(params[:contact_form])
    
    @contact_form.save
  
    respond_with @contact_form
    # respond_to do |format|
    #   if @contact_form.save
    #     format.html { redirect_to contact_forms_path, notice: 'Contact form was successfully created.' }
    #     format.json { render json: @contact_form, status: :created, location: @contact_form }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @contact_form.errors, status: :unprocessable_entity }
    #   end
    # end
  end
end

app/helpers/admin/contact_forms_helper.rb
module Admin::ContactFormsHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/views/admin/contact_forms/index.html.erb
<h1>Listing contact_forms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Subject</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @contact_forms.each do |contact_form| %>
  <tr>
    <td><%= contact_form.name %></td>
    <td><%= contact_form.email %></td>
    <td><%= contact_form.subject %></td>
    <td><%= contact_form.description %></td>
    <td><%= link_to 'Show', admin_contact_form %></td>
    <td><%= link_to 'Destroy', admin_contact_form, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/admin/contact_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact_form.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact_form.email %>
</p>

<p>
  <b>Subject:</b>
  <%= @contact_form.subject %>
</p>

<p>
  <b>Description:</b>
  <%= @contact_form.description %>
</p>


<%= link_to 'Back', admin_contact_forms_path %>