config/routes.rb
Ralencar::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  

  resources :contact_forms

  resources :jobs

  resources :posts do
    member do
      get 'hasNext'
      get 'to'
      get 'count'
      get 'index_of'
      get 'menu'
    end
  end

  match 'posts/:first/to/:last', :controller => 'posts', :action => 'find'
    

    namespace :admin do
      resources :posts
      resources :jobs
      resources :contact_forms

    end

  
  root :to => 'posts#show'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	layout 'admin'
	
	# GET /posts
	# GET /posts.json
	def index
		
		@posts = Post.all
	
		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @posts }
		end
	end
	
	# GET /posts/1
	# GET /posts/1.json
	def show
		@post = Post.find(params[:id])
	
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @post }
		end
	end
	
	# GET /posts/new
	# GET /posts/new.json
	def new
		@post = Post.new
	
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @post }
		end
	end
	
	# GET /posts/1/edit
	def edit
		@post = Post.find(params[:id])
	end
	
	# POST /posts
	# POST /posts.json
	def create
		@post = Post.new(params[:post])
	
		respond_to do |format|
			if @post.save
				format.html { redirect_to :admin, @post, notice: 'Post was successfully created.' }
				format.json { render json: @post, status: :created, location: @post }
			else
				format.html { render action: "new" }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end
	
	# PUT /posts/1
	# PUT /posts/1.json
	def update
		@post = Post.find(params[:id])
	
		respond_to do |format|
			if @post.update_attributes(params[:post])
				format.html { redirect_to :admin, @post, notice: 'Post was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end
	
	# DELETE /posts/1
	# DELETE /posts/1.json
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
	
		respond_to do |format|
			format.html { redirect_to :admin, posts_url }
			format.json { head :no_content }
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'public'
  
  # GET /posts
  # GET /posts.json
  def index
    @post = Post.order("date DESC").last
    @count = Post.all.count
    @num_nexts = Post.where("date > :post_date", {:post_date => @post.date}).count
    @index_of = 0
    @contact_form = ContactForm.new(params[:contact_form])
    
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post }
    end

  end
  
  # GET /posts/count
  def count
  
    @posts = Post.all.count
  
    respond_to do |format|
      format.json { render json: @posts }
    end
  end	

  # GET /posts/menu
  def menu
  
    @posts = Post.order("date DESC")
  
    respond_to do |format|
      format.json { render json: @posts }
    end
  end	

  # GET /posts/1
  # GET /posts/1.json
  def show
    if params[:id]
      @post = Post.find(params[:id]) 
    else
      @post = Post.order("date DESC").last
    end
    
    @jobs = Job.all
    @count = Post.all.count
    @num_nexts = Post.where("date > :post_date", {:post_date => @post.date}).count
    @contact_form = ContactForm.new
        
    if params[:index_of]
      @index_of = params[:index_of]
    else
      @index_of = @count - @num_nexts
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def last
    @post = Post.last

    respond_to do |format|
      format.html # last.html.erb
      format.json { render json: @post }
    end
  end

  def hasNext
    @hasNext = Post.exists?(params[:id].to_i + 1)
    respond_to do |format|
      format.json { 
        render json: {
          :hasNext => @hasNext
        }
      }
    end
  end
  
  def index_of
    @count = Post.all.count
    post = Post.find(params[:id])
    @num_nexts = Post.where("date > :post_date", {:post_date => post.date}).count
    @index_of = @count - @num_nexts
    
    respond_to do |format|
      format.json { 
        render json: {
          :count => @count, 
          :num_nexts => @num_nexts,
          :index_of => @index_of
        }
      }
    end
  end


  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # GET /posts/1/to/6
  def find
    if params[:first]
      if !params[:last]
        amount = 1
      else
        amount = params[:last].to_i - params[:first].to_i + 1
      end
      @posts = Post.order("date DESC").offset(params[:first].to_i-1).limit(amount)
    else 
      @posts = Post.find_all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <script type="text/javascript">
    $(function() {
      $('textarea').tinymce({
        theme: 'advanced',
				skin: 'default',
				theme_advanced_toolbar_location : "top",
				theme_advanced_toolbar_align : "left",
				theme_advanced_buttons1 : "bold,italic,underline,numlist,bullist,link,image,code,forecolor,blockquote",
				theme_advanced_buttons2 : "",
				theme_advanced_buttons3 : "",
				
      });
    });
  </script>

<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_post_path(@post) %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %> !!!!! <%=@renato%> !!!</td>
    <td><%= post.date %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', admin_post_path(post) %></td>
    <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
    <td><%= link_to 'Destroy', admin_post_path(post), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_admin_post_path %>

app/views/admin/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Date:</b>
  <%= @post.date %>
</p>

<p>
  <b>Content:</b>
  <%= raw(@post.content) %>
</p>


<%= link_to 'Edit', edit_admin_post_path(@post) %> |
<%= link_to 'Back', admin_posts_path %>